name: CI

on:
  push:
    branches: [main]

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "build.zig"
      - "build.zig.zon"

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: ["master", "0.14.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        optimize: [ReleaseSafe, ReleaseFast]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}
          use-cache: false

      - name: Run `build`
        run: zig build ${{ matrix.build-options }} -Doptimize=${{ matrix.optimize }} --summary all

